# Generated by Django 4.2.7 on 2025-11-16 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('question_count', models.PositiveIntegerField(default=20)),
                ('questions', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready'), ('error', 'Error')], default='generating', max_length=20)),
                ('generation_error', models.TextField(blank=True)),
                ('generation_time_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tests', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('grade', models.CharField(choices=[('A', 'A - Excellent (90-100%)'), ('B', 'B - Good (80-89%)'), ('C', 'C - Average (70-79%)'), ('D', 'D - Passing (60-69%)'), ('F', 'F - Fail (Below 60%)')], default='F', max_length=1)),
                ('passed', models.BooleanField(default=False)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('incorrect_count', models.PositiveIntegerField(default=0)),
                ('results_detail', models.JSONField(default=list)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='documents.documenttest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'completed_at'], name='documents_t_user_id_71b796_idx'), models.Index(fields=['test', 'user'], name='documents_t_test_id_e1bff6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='documenttest',
            index=models.Index(fields=['document', 'created_by'], name='documents_d_documen_bf7706_idx'),
        ),
        migrations.AddIndex(
            model_name='documenttest',
            index=models.Index(fields=['created_by', 'created_at'], name='documents_d_created_c7b56a_idx'),
        ),
    ]
