# Generated by Django 4.2.7 on 2025-09-02 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=50)),
                ('model_identifier', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('max_tokens', models.IntegerField(default=1000000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_ai_models',
            },
        ),
        migrations.RemoveField(
            model_name='aiprompttemplate',
            name='created_by',
        ),
        migrations.AlterModelOptions(
            name='studysession',
            options={'ordering': ['-started_at']},
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_user_id_cfac6a_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_documen_7a0ac0_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_user_id_6e2bb0_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_45d255_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_3154fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='studysession',
            name='chat_studys_user_id_1f81b6_idx',
        ),
        migrations.RemoveIndex(
            model_name='studysession',
            name='chat_studys_documen_9cd669_idx',
        ),
        migrations.RemoveIndex(
            model_name='studysession',
            name='chat_studys_user_id_8dbd57_idx',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='completed_at',
            new_name='ended_at',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='title',
            new_name='session_name',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='description',
            new_name='session_notes',
        ),
        migrations.RenameField(
            model_name='studysession',
            old_name='created_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='ai_context_limit',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='ai_temperature',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='last_message_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='total_tokens_used',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_model_used',
        ),
        migrations.RemoveField(
            model_name='message',
            name='ai_sources',
        ),
        migrations.RemoveField(
            model_name='message',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_feedback',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user_rating',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='completion_percentage',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='document',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='flashcard_data',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='quiz_data',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='score',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='summary_data',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='time_spent_minutes',
        ),
        migrations.RemoveField(
            model_name='studysession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='conversation',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='conversations', to='documents.document'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversation',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='questions_asked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studysession',
            name='topics_covered',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='tokens_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_sessions', to='chat.conversation'),
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='chat_conversations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='chat_messages',
        ),
        migrations.AlterModelTable(
            name='studysession',
            table='chat_study_sessions',
        ),
        migrations.DeleteModel(
            name='AIPromptTemplate',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.aimodel'),
        ),
    ]
